//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSPMWatchDog.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\atspm\\config\\signals_MJB_4-20-19.json")]
        public string SignalConfigFile {
            get {
                return ((string)(this["SignalConfigFile"]));
            }
            set {
                this["SignalConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\atspm\\dat_processed")]
        public string DATfolder {
            get {
                return ((string)(this["DATfolder"]));
            }
            set {
                this["DATfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sgault@yahoo.com")]
        public string EmailNotificationsTo {
            get {
                return ((string)(this["EmailNotificationsTo"]));
            }
            set {
                this["EmailNotificationsTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateEmail {
            get {
                return ((bool)(this["GenerateEmail"]));
            }
            set {
                this["GenerateEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Traffic Signal ATSPM Alerts in Mount Joy Borough")]
        public string EmailSubject {
            get {
                return ((string)(this["EmailSubject"]));
            }
            set {
                this["EmailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ConsecutiveCount {
            get {
                return ((int)(this["ConsecutiveCount"]));
            }
            set {
                this["ConsecutiveCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mtjoytwp.engineer@gmail.com")]
        public string DefaultEmailAddress {
            get {
                return ((string)(this["DefaultEmailAddress"]));
            }
            set {
                this["DefaultEmailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LowHitThreshold {
            get {
                return ((int)(this["LowHitThreshold"]));
            }
            set {
                this["LowHitThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int MinimumRecords {
            get {
                return ((int)(this["MinimumRecords"]));
            }
            set {
                this["MinimumRecords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MinPhaseTerminations {
            get {
                return ((int)(this["MinPhaseTerminations"]));
            }
            set {
                this["MinPhaseTerminations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double PercentThreshold {
            get {
                return ((double)(this["PercentThreshold"]));
            }
            set {
                this["PercentThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int PreviousDayPMPeakEnd {
            get {
                return ((int)(this["PreviousDayPMPeakEnd"]));
            }
            set {
                this["PreviousDayPMPeakEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int PreviousDayPMPeakStart {
            get {
                return ((int)(this["PreviousDayPMPeakStart"]));
            }
            set {
                this["PreviousDayPMPeakStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ScanDayEndHour {
            get {
                return ((int)(this["ScanDayEndHour"]));
            }
            set {
                this["ScanDayEndHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ScanDayStartHour {
            get {
                return ((int)(this["ScanDayStartHour"]));
            }
            set {
                this["ScanDayStartHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WeekdayOnly {
            get {
                return ((bool)(this["WeekdayOnly"]));
            }
            set {
                this["WeekdayOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MaximumPedestrianEvents {
            get {
                return ((int)(this["MaximumPedestrianEvents"]));
            }
            set {
                this["MaximumPedestrianEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmailAllErrors {
            get {
                return ((bool)(this["EmailAllErrors"]));
            }
            set {
                this["EmailAllErrors"] = value;
            }
        }
    }
}
